name = "GigaSOM"
uuid = "6938aec0-5167-11e9-0fa5-b3a57f4853a7"
authors = ["laurentheirendt <laurent.heirendt@uni.lu>"]
version = "0.0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]